version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      # Uncomment below if you want HTTPS
      # - "443:443"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy-headers.conf:/etc/nginx/proxy-headers.conf
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - webapp
      - adminapp
    networks:
      - test-app-bridge

  webapp:
    image: nginx:alpine
    container_name: test-web-image
    volumes:
    - ./admin:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - test-app-bridge

  adminapp:
    image: test-admin-image
    container_name: admin-test
    volumes:
      - ./admin:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - test-app-bridge

networks:
  test-app-bridge:
    driver: bridge
