version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy-headers.conf:/etc/nginx/proxy-headers.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - test-app

  app1:
    image: nginx:alpine
    container_name: app1
    volumes:
      - ./app1:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - test-app

  app2:
    image: nginx:alpine
    container_name: app2
    volumes:
      - ./app2:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - test-app

  app3:
    image: nginx:alpine
    container_name: app3
    volumes:
      - ./app3:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - test-app

networks:
  test-app:
    driver: bridge
