# version: '3.8'

services:
  https-nginx:
    image: nginx:latest
    container_name: https-nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./https-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/nginx/certs:ro
    depends_on:
    - nginx-proxy
    networks:
    - test-app

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
    - "8000:80"
    volumes:
    - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/proxy-headers.conf:/etc/nginx/proxy-headers.conf:ro
    depends_on:
    - app1
    - app2
    - app3
    networks:
    - test-app

  app1:
    image: nginx:alpine
    container_name: app1
    volumes:
    - ./app1:/usr/share/nginx/html:ro
    expose:
    - "80"
    networks:
    - test-app

networks:
  test-app:
    driver: bridge
